# Generated by Django 2.2.4 on 2023-07-14 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('the_app', '0004_auto_20230713_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental', to='the_app.Car'),
        ),
    ]
